/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using BigCommerceAPI.PCL.Controllers;
using BigCommerceAPI.PCL.Http.Client;

namespace BigCommerceAPI.PCL
{
    public partial class BigCommerceAPIClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public BigCommerceAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public BigCommerceAPIClient(string storeId)
        {
            Configuration.StoreId = storeId;
        }
    }
}