/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    public class BulkPricingRule : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? amount;
        private int? id;
        private int? quantityMax;
        private int? quantityMin;
        private object type;

        /// <summary>
        /// The value of the adjusted by the bulk pricing rule.
        /// </summary>
        [JsonProperty("amount")]
        public int? Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// The ID of the bulk pricing rule.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The minimum inclusive quantity of a product to satisfy this rule. Must be greater than or equal to zero.
        /// </summary>
        [JsonProperty("quantity_max")]
        public int? QuantityMax 
        { 
            get 
            {
                return this.quantityMax; 
            } 
            set 
            {
                this.quantityMax = value;
                onPropertyChanged("QuantityMax");
            }
        }

        /// <summary>
        /// The maximum inclusive quantity of a product to satisfy this rule. Must be greater than the min value, unless this field has a value of 0 (zero), in which case there will be no maximum bound for this rule.
        /// </summary>
        [JsonProperty("quantity_min")]
        public int? QuantityMin 
        { 
            get 
            {
                return this.quantityMin; 
            } 
            set 
            {
                this.quantityMin = value;
                onPropertyChanged("QuantityMin");
            }
        }

        /// <summary>
        /// The type of adjument that is made, 'price' - The adjument amount per product, 'percent' - The adjustment as a percent of the original price, 'fixed' - the adjusted absolute price of the product.
        /// </summary>
        [JsonProperty("type")]
        public object Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 