/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    public class CollectionMeta : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? count;
        private int? currentPage;
        private Links links;
        private int? perPage;
        private int? total;
        private int? totalPages;

        /// <summary>
        /// Total number of items in the collection
        /// </summary>
        [JsonProperty("count")]
        public int? Count 
        { 
            get 
            {
                return this.count; 
            } 
            set 
            {
                this.count = value;
                onPropertyChanged("Count");
            }
        }

        /// <summary>
        /// The page you are currently on within the collection.
        /// </summary>
        [JsonProperty("current_page")]
        public int? CurrentPage 
        { 
            get 
            {
                return this.currentPage; 
            } 
            set 
            {
                this.currentPage = value;
                onPropertyChanged("CurrentPage");
            }
        }

        /// <summary>
        /// Pagination links for the previous and next parts of the whole collection.
        /// </summary>
        [JsonProperty("links")]
        public Links Links 
        { 
            get 
            {
                return this.links; 
            } 
            set 
            {
                this.links = value;
                onPropertyChanged("Links");
            }
        }

        /// <summary>
        /// The number of items returned in the collection per page, controlled by the `limit` parameter
        /// </summary>
        [JsonProperty("per_page")]
        public int? PerPage 
        { 
            get 
            {
                return this.perPage; 
            } 
            set 
            {
                this.perPage = value;
                onPropertyChanged("PerPage");
            }
        }

        /// <summary>
        /// Total number of items returned in the result set.
        /// </summary>
        [JsonProperty("total")]
        public int? Total 
        { 
            get 
            {
                return this.total; 
            } 
            set 
            {
                this.total = value;
                onPropertyChanged("Total");
            }
        }

        /// <summary>
        /// The total number of pages in the collection.
        /// </summary>
        [JsonProperty("total_pages")]
        public int? TotalPages 
        { 
            get 
            {
                return this.totalPages; 
            } 
            set 
            {
                this.totalPages = value;
                onPropertyChanged("TotalPages");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 