/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    public class CustomUrl : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private bool? isCustomized;
        private string url;

        /// <summary>
        /// Returns true if the url has been changed from it's default state (the auto-assigned url BigCommerce provides)
        /// </summary>
        [JsonProperty("is_customized")]
        public bool? IsCustomized 
        { 
            get 
            {
                return this.isCustomized; 
            } 
            set 
            {
                this.isCustomized = value;
                onPropertyChanged("IsCustomized");
            }
        }

        /// <summary>
        /// Product url on the store front.
        /// </summary>
        [JsonProperty("url")]
        public string Url 
        { 
            get 
            {
                return this.url; 
            } 
            set 
            {
                this.url = value;
                onPropertyChanged("Url");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 