/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum DefaultProductSortEnum
    {
        USE_STORE_SETTINGS, //TODO: Write general description for this method
        FEATURED, //TODO: Write general description for this method
        NEWEST, //TODO: Write general description for this method
        BEST_SELLING, //TODO: Write general description for this method
        ALPHA_ASC, //TODO: Write general description for this method
        ALPHA_DESC, //TODO: Write general description for this method
        AVG_CUSTOMER_REVIEW, //TODO: Write general description for this method
        PRICE_ASC, //TODO: Write general description for this method
        PRICE_DESC, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type DefaultProductSortEnum
    /// </summary>
    public static class DefaultProductSortEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "use_store_settings", "featured", "newest", "best_selling", "alpha_asc", "alpha_desc", "avg_customer_review", "price_asc", "price_desc" };

        /// <summary>
        /// Converts a DefaultProductSortEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The DefaultProductSortEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(DefaultProductSortEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case DefaultProductSortEnum.USE_STORE_SETTINGS:
                case DefaultProductSortEnum.FEATURED:
                case DefaultProductSortEnum.NEWEST:
                case DefaultProductSortEnum.BEST_SELLING:
                case DefaultProductSortEnum.ALPHA_ASC:
                case DefaultProductSortEnum.ALPHA_DESC:
                case DefaultProductSortEnum.AVG_CUSTOMER_REVIEW:
                case DefaultProductSortEnum.PRICE_ASC:
                case DefaultProductSortEnum.PRICE_DESC:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of DefaultProductSortEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of DefaultProductSortEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<DefaultProductSortEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into DefaultProductSortEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed DefaultProductSortEnum value</returns>
        public static DefaultProductSortEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type DefaultProductSortEnum", value));

            return (DefaultProductSortEnum) index;
        }
    }
} 