/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    public class Modifier : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private OptionConfig config;
        private string displayName;
        private int? id;
        private string name;
        private int? productId;
        private ModifierTypeEnum? type;
        private List<ModifierValue> values;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("config")]
        public OptionConfig Config 
        { 
            get 
            {
                return this.config; 
            } 
            set 
            {
                this.config = value;
                onPropertyChanged("Config");
            }
        }

        /// <summary>
        /// The name of the option, as shown on the storefront.
        /// </summary>
        [JsonProperty("display_name")]
        public string DisplayName 
        { 
            get 
            {
                return this.displayName; 
            } 
            set 
            {
                this.displayName = value;
                onPropertyChanged("DisplayName");
            }
        }

        /// <summary>
        /// The unique numeric ID of the modifier; increments sequentially.
        /// </summary>
        [JsonProperty("id")]
        public int? Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// The unique option name; auto-generated from the display name, a timestamp, and the product ID.
        /// </summary>
        [JsonProperty("name")]
        public string Name 
        { 
            get 
            {
                return this.name; 
            } 
            set 
            {
                this.name = value;
                onPropertyChanged("Name");
            }
        }

        /// <summary>
        /// The unique numeric ID of the product to which the option belongs.
        /// </summary>
        [JsonProperty("product_id")]
        public int? ProductId 
        { 
            get 
            {
                return this.productId; 
            } 
            set 
            {
                this.productId = value;
                onPropertyChanged("ProductId");
            }
        }

        /// <summary>
        /// The type of modifier, which determines how it will display on the storefront. For reference, former v2 API values: 
        /// D = date, C = checkbox, F = file, T = text, MT = multi_line_text, N = numbers_only_text, RB = radio_buttons, 
        /// RT = rectangles, S = dropdown, P = product_list, PI = product_list_with_images, CS = swatch.
        /// </summary>
        [JsonProperty("type", ItemConverterType = typeof(StringValuedEnumConverter))]
        public ModifierTypeEnum? Type 
        { 
            get 
            {
                return this.type; 
            } 
            set 
            {
                this.type = value;
                onPropertyChanged("Type");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("values")]
        public List<ModifierValue> Values 
        { 
            get 
            {
                return this.values; 
            } 
            set 
            {
                this.values = value;
                onPropertyChanged("Values");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 