/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum OptionTypeEnum
    {
        RADIO_BUTTONS, //TODO: Write general description for this method
        RECTANGLES, //TODO: Write general description for this method
        DROPDOWN, //TODO: Write general description for this method
        PRODUCT_LIST, //TODO: Write general description for this method
        PRODUCT_LIST_WITH_IMAGES, //TODO: Write general description for this method
        SWATCH, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type OptionTypeEnum
    /// </summary>
    public static class OptionTypeEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "radio_buttons", "rectangles", "dropdown", "product_list", "product_list_with_images", "swatch" };

        /// <summary>
        /// Converts a OptionTypeEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The OptionTypeEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(OptionTypeEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case OptionTypeEnum.RADIO_BUTTONS:
                case OptionTypeEnum.RECTANGLES:
                case OptionTypeEnum.DROPDOWN:
                case OptionTypeEnum.PRODUCT_LIST:
                case OptionTypeEnum.PRODUCT_LIST_WITH_IMAGES:
                case OptionTypeEnum.SWATCH:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of OptionTypeEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of OptionTypeEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<OptionTypeEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into OptionTypeEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed OptionTypeEnum value</returns>
        public static OptionTypeEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type OptionTypeEnum", value));

            return (OptionTypeEnum) index;
        }
    }
} 