/*
 * BigCommerceAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 04/27/2020
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using BigCommerceAPI.PCL;
using BigCommerceAPI.PCL.Utilities;

namespace BigCommerceAPI.PCL.Models
{
    public class ResourceImage : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string imageFile;
        private string imageUrl;

        /// <summary>
        /// A public URL for a GIF, JPEG, or PNG image.
        /// </summary>
        [JsonProperty("image_file")]
        public string ImageFile 
        { 
            get 
            {
                return this.imageFile; 
            } 
            set 
            {
                this.imageFile = value;
                onPropertyChanged("ImageFile");
            }
        }

        /// <summary>
        /// A public URL for a GIF, JPEG, or PNG image.
        /// </summary>
        [JsonProperty("image_url")]
        public string ImageUrl 
        { 
            get 
            {
                return this.imageUrl; 
            } 
            set 
            {
                this.imageUrl = value;
                onPropertyChanged("ImageUrl");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 