using System;
using System.Linq;

namespace Fsl.BigCommerce.Api.Connector.Services
{
    public class CountryCodes
    {
        private static readonly (string Code2, string Code3)[] CountryCodeMap = new (string Code2, string Code3)[]
        {
            (Code2: "AF", Code3: "AFG"),
            (Code2: "AL", Code3: "ALB"),
            (Code2: "DZ", Code3: "DZA"),
            (Code2: "AS", Code3: "ASM"),
            (Code2: "AD", Code3: "AND"),
            (Code2: "AO", Code3: "AGO"),
            (Code2: "AI", Code3: "AIA"),
            (Code2: "AQ", Code3: "ATA"),
            (Code2: "AG", Code3: "ATG"),
            (Code2: "AR", Code3: "ARG"),
            (Code2: "AM", Code3: "ARM"),
            (Code2: "AW", Code3: "ABW"),
            (Code2: "AU", Code3: "AUS"),
            (Code2: "AT", Code3: "AUT"),
            (Code2: "AZ", Code3: "AZE"),
            (Code2: "BS", Code3: "BHS"),
            (Code2: "BH", Code3: "BHR"),
            (Code2: "BD", Code3: "BGD"),
            (Code2: "BB", Code3: "BRB"),
            (Code2: "BY", Code3: "BLR"),
            (Code2: "BE", Code3: "BEL"),
            (Code2: "BZ", Code3: "BLZ"),
            (Code2: "BJ", Code3: "BEN"),
            (Code2: "BM", Code3: "BMU"),
            (Code2: "BT", Code3: "BTN"),
            (Code2: "BO", Code3: "BOL"),
            (Code2: "BA", Code3: "BIH"),
            (Code2: "BW", Code3: "BWA"),
            (Code2: "BV", Code3: "BVT"),
            (Code2: "BR", Code3: "BRA"),
            (Code2: "IO", Code3: "IOT"),
            (Code2: "VG", Code3: "VGB"),
            (Code2: "BN", Code3: "BRN"),
            (Code2: "BG", Code3: "BGR"),
            (Code2: "BF", Code3: "BFA"),
            (Code2: "BI", Code3: "BDI"),
            (Code2: "KH", Code3: "KHM"),
            (Code2: "CM", Code3: "CMR"),
            (Code2: "CA", Code3: "CAN"),
            (Code2: "CV", Code3: "CPV"),
            (Code2: "KY", Code3: "CYM"),
            (Code2: "CF", Code3: "CAF"),
            (Code2: "TD", Code3: "TCD"),
            (Code2: "CL", Code3: "CHL"),
            (Code2: "CN", Code3: "CHN"),
            (Code2: "CX", Code3: "CXR"),
            (Code2: "CC", Code3: "CCK"),
            (Code2: "CO", Code3: "COL"),
            (Code2: "KM", Code3: "COM"),
            (Code2: "CD", Code3: "COD"),
            (Code2: "CG", Code3: "COG"),
            (Code2: "CK", Code3: "COK"),
            (Code2: "CR", Code3: "CRI"),
            (Code2: "CI", Code3: "CIV"),
            (Code2: "CU", Code3: "CUB"),
            (Code2: "CY", Code3: "CYP"),
            (Code2: "CZ", Code3: "CZE"),
            (Code2: "DK", Code3: "DNK"),
            (Code2: "DJ", Code3: "DJI"),
            (Code2: "DM", Code3: "DMA"),
            (Code2: "DO", Code3: "DOM"),
            (Code2: "EC", Code3: "ECU"),
            (Code2: "EG", Code3: "EGY"),
            (Code2: "SV", Code3: "SLV"),
            (Code2: "GQ", Code3: "GNQ"),
            (Code2: "ER", Code3: "ERI"),
            (Code2: "EE", Code3: "EST"),
            (Code2: "ET", Code3: "ETH"),
            (Code2: "FO", Code3: "FRO"),
            (Code2: "FK", Code3: "FLK"),
            (Code2: "FJ", Code3: "FJI"),
            (Code2: "FI", Code3: "FIN"),
            (Code2: "FR", Code3: "FRA"),
            (Code2: "GF", Code3: "GUF"),
            (Code2: "PF", Code3: "PYF"),
            (Code2: "TF", Code3: "ATF"),
            (Code2: "GA", Code3: "GAB"),
            (Code2: "GM", Code3: "GMB"),
            (Code2: "GE", Code3: "GEO"),
            (Code2: "DE", Code3: "DEU"),
            (Code2: "GH", Code3: "GHA"),
            (Code2: "GI", Code3: "GIB"),
            (Code2: "GR", Code3: "GRC"),
            (Code2: "GL", Code3: "GRL"),
            (Code2: "GD", Code3: "GRD"),
            (Code2: "GP", Code3: "GLP"),
            (Code2: "GU", Code3: "GUM"),
            (Code2: "GT", Code3: "GTM"),
            (Code2: "GN", Code3: "GIN"),
            (Code2: "GW", Code3: "GNB"),
            (Code2: "GY", Code3: "GUY"),
            (Code2: "HT", Code3: "HTI"),
            (Code2: "HM", Code3: "HMD"),
            (Code2: "VA", Code3: "VAT"),
            (Code2: "HN", Code3: "HND"),
            (Code2: "HK", Code3: "HKG"),
            (Code2: "HR", Code3: "HRV"),
            (Code2: "HU", Code3: "HUN"),
            (Code2: "IS", Code3: "ISL"),
            (Code2: "IN", Code3: "IND"),
            (Code2: "ID", Code3: "IDN"),
            (Code2: "IR", Code3: "IRN"),
            (Code2: "IQ", Code3: "IRQ"),
            (Code2: "IE", Code3: "IRL"),
            (Code2: "IL", Code3: "ISR"),
            (Code2: "IT", Code3: "ITA"),
            (Code2: "JM", Code3: "JAM"),
            (Code2: "JP", Code3: "JPN"),
            (Code2: "JO", Code3: "JOR"),
            (Code2: "KZ", Code3: "KAZ"),
            (Code2: "KE", Code3: "KEN"),
            (Code2: "KI", Code3: "KIR"),
            (Code2: "KP", Code3: "PRK"),
            (Code2: "KR", Code3: "KOR"),
            (Code2: "KW", Code3: "KWT"),
            (Code2: "KG", Code3: "KGZ"),
            (Code2: "LA", Code3: "LAO"),
            (Code2: "LV", Code3: "LVA"),
            (Code2: "LB", Code3: "LBN"),
            (Code2: "LS", Code3: "LSO"),
            (Code2: "LR", Code3: "LBR"),
            (Code2: "LY", Code3: "LBY"),
            (Code2: "LI", Code3: "LIE"),
            (Code2: "LT", Code3: "LTU"),
            (Code2: "LU", Code3: "LUX"),
            (Code2: "MO", Code3: "MAC"),
            (Code2: "MK", Code3: "MKD"),
            (Code2: "MG", Code3: "MDG"),
            (Code2: "MW", Code3: "MWI"),
            (Code2: "MY", Code3: "MYS"),
            (Code2: "MV", Code3: "MDV"),
            (Code2: "ML", Code3: "MLI"),
            (Code2: "MT", Code3: "MLT"),
            (Code2: "MH", Code3: "MHL"),
            (Code2: "MQ", Code3: "MTQ"),
            (Code2: "MR", Code3: "MRT"),
            (Code2: "MU", Code3: "MUS"),
            (Code2: "YT", Code3: "MYT"),
            (Code2: "MX", Code3: "MEX"),
            (Code2: "FM", Code3: "FSM"),
            (Code2: "MD", Code3: "MDA"),
            (Code2: "MC", Code3: "MCO"),
            (Code2: "MN", Code3: "MNG"),
            (Code2: "MS", Code3: "MSR"),
            (Code2: "MA", Code3: "MAR"),
            (Code2: "MZ", Code3: "MOZ"),
            (Code2: "MM", Code3: "MMR"),
            (Code2: "NA", Code3: "NAM"),
            (Code2: "NR", Code3: "NRU"),
            (Code2: "NP", Code3: "NPL"),
            (Code2: "AN", Code3: "ANT"),
            (Code2: "NL", Code3: "NLD"),
            (Code2: "NC", Code3: "NCL"),
            (Code2: "NZ", Code3: "NZL"),
            (Code2: "NI", Code3: "NIC"),
            (Code2: "NE", Code3: "NER"),
            (Code2: "NG", Code3: "NGA"),
            (Code2: "NU", Code3: "NIU"),
            (Code2: "NF", Code3: "NFK"),
            (Code2: "MP", Code3: "MNP"),
            (Code2: "NO", Code3: "NOR"),
            (Code2: "OM", Code3: "OMN"),
            (Code2: "PK", Code3: "PAK"),
            (Code2: "PW", Code3: "PLW"),
            (Code2: "PS", Code3: "PSE"),
            (Code2: "PA", Code3: "PAN"),
            (Code2: "PG", Code3: "PNG"),
            (Code2: "PY", Code3: "PRY"),
            (Code2: "PE", Code3: "PER"),
            (Code2: "PH", Code3: "PHL"),
            (Code2: "PN", Code3: "PCN"),
            (Code2: "PL", Code3: "POL"),
            (Code2: "PT", Code3: "PRT"),
            (Code2: "PR", Code3: "PRI"),
            (Code2: "QA", Code3: "QAT"),
            (Code2: "RE", Code3: "REU"),
            (Code2: "RO", Code3: "ROU"),
            (Code2: "RU", Code3: "RUS"),
            (Code2: "RW", Code3: "RWA"),
            (Code2: "SH", Code3: "SHN"),
            (Code2: "KN", Code3: "KNA"),
            (Code2: "LC", Code3: "LCA"),
            (Code2: "PM", Code3: "SPM"),
            (Code2: "VC", Code3: "VCT"),
            (Code2: "WS", Code3: "WSM"),
            (Code2: "SM", Code3: "SMR"),
            (Code2: "ST", Code3: "STP"),
            (Code2: "SA", Code3: "SAU"),
            (Code2: "SN", Code3: "SEN"),
            (Code2: "CS", Code3: "SCG"),
            (Code2: "SC", Code3: "SYC"),
            (Code2: "SL", Code3: "SLE"),
            (Code2: "SG", Code3: "SGP"),
            (Code2: "SK", Code3: "SVK"),
            (Code2: "SI", Code3: "SVN"),
            (Code2: "SB", Code3: "SLB"),
            (Code2: "SO", Code3: "SOM"),
            (Code2: "ZA", Code3: "ZAF"),
            (Code2: "GS", Code3: "SGS"),
            (Code2: "ES", Code3: "ESP"),
            (Code2: "LK", Code3: "LKA"),
            (Code2: "SD", Code3: "SDN"),
            (Code2: "SR", Code3: "SUR"),
            (Code2: "SJ", Code3: "SJM"),
            (Code2: "SZ", Code3: "SWZ"),
            (Code2: "SE", Code3: "SWE"),
            (Code2: "CH", Code3: "CHE"),
            (Code2: "SY", Code3: "SYR"),
            (Code2: "TW", Code3: "TWN"),
            (Code2: "TJ", Code3: "TJK"),
            (Code2: "TZ", Code3: "TZA"),
            (Code2: "TH", Code3: "THA"),
            (Code2: "TL", Code3: "TLS"),
            (Code2: "TG", Code3: "TGO"),
            (Code2: "TK", Code3: "TKL"),
            (Code2: "TO", Code3: "TON"),
            (Code2: "TT", Code3: "TTO"),
            (Code2: "TN", Code3: "TUN"),
            (Code2: "TR", Code3: "TUR"),
            (Code2: "TM", Code3: "TKM"),
            (Code2: "TC", Code3: "TCA"),
            (Code2: "TV", Code3: "TUV"),
            (Code2: "VI", Code3: "VIR"),
            (Code2: "UG", Code3: "UGA"),
            (Code2: "UA", Code3: "UKR"),
            (Code2: "AE", Code3: "ARE"),
            (Code2: "GB", Code3: "GBR"),
            (Code2: "UM", Code3: "UMI"),
            (Code2: "US", Code3: "USA"),
            (Code2: "UY", Code3: "URY"),
            (Code2: "UZ", Code3: "UZB"),
            (Code2: "VU", Code3: "VUT"),
            (Code2: "VE", Code3: "VEN"),
            (Code2: "VN", Code3: "VNM"),
            (Code2: "WF", Code3: "WLF"),
            (Code2: "EH", Code3: "ESH"),
            (Code2: "YE", Code3: "YEM"),
            (Code2: "ZM", Code3: "ZMB"),
            (Code2: "ZW", Code3: "ZWE"),
        };

        public const string DefaultAlpha2 = "US";
        public const string DefaultAlpha3 = "USA";

        public static string ToAlpha2 (string code)
        {
            if (string.IsNullOrWhiteSpace(code))
                return null;

            (string Code2, string Code3)? map = CountryCodeMap.FirstOrDefault(entry => string.Equals(code.Length == 2 ? entry.Code2 : entry.Code3, code, StringComparison.OrdinalIgnoreCase));

            return map?.Code2;
        }

        public static string ToAlpha3(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
                return null;

            (string Code2, string Code3)? map = CountryCodeMap.FirstOrDefault(entry => string.Equals(code.Length == 3 ? entry.Code3 : entry.Code2, code, StringComparison.OrdinalIgnoreCase));

            return map?.Code3;
        }
    }
}
